# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1062, 792)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/icons/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        Form.setWindowIcon(icon)
        Form.setLayoutDirection(QtCore.Qt.RightToLeft)
        Form.setStyleSheet(
            "QWidget {\n"
            "\n"
            "            background-color :  rgb(255, 255, 255) ; \n"
            "        \n"
            "            border-radius : 5%;         \n"
            "        padding : 0 ; \n"
            "     margin : 0 ; \n"
            "\n"
            "\n"
            "}"
        )
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet(
            "\n"
            "  QTabWidget::pane {\n"
            "    margin : 5px  ;\n"
            "\n"
            "            border-radius : 3% ;\n"
            "\n"
            "\n"
            "        }\n"
            "\n"
            "\n"
            "\n"
            "QTabWidget::tab-bar {\n"
            "    alignment : right     ;\n"
            "\n"
            "\n"
            "}\n"
            "\n"
            "QTabBar\n"
            "{\n"
            "\n"
            '        font: 11pt "Ravie";\n'
            "    font-weight : bold ;\n"
            "\n"
            "}\n"
            "QTabBar::tab {\n"
            "\n"
            "    margin-top : 10px;\n"
            "    background-color : #36304A; \n"
            "    color :  rgb(157, 157, 157)   ;\n"
            "    padding : 5px ;\n"
            "\n"
            "    border : 1px solid transparent    ;\n"
            "    border-radius : 3%;\n"
            "\n"
            "\n"
            "}\n"
            "\n"
            "QTabBar::tab::selected {\n"
            "    background-color  :  rgb(95, 85, 131) ; \n"
            "    color : white    ; \n"
            "\n"
            "\n"
            "\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "   QTabBar::tab:hover {\n"
            "\n"
            "\n"
            "        }"
        )
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/icons/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.tabWidget.addTab(self.tab_1, icon1, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("Form", "تكاليف الشركات ")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_3), _translate("Form", "تكاليف الاشخاص")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("Form", "مصاريف الشركة")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_1), _translate("Form", "الصفحه الرئيسية")
        )
